import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export interface AgentData {
  name: string;
  id: string;
  description: string;
  longDescription: string;
  category: string;
  rating: number;
  downloads: string;
  verified: boolean;
  price: string;
  image: string;
  trustScore: number;
  developer: string;
  stats: {
    successRate: number;
    uptime: number;
  };
  howItWorks: string;
  keyFeatures: string[];
  audit: { daoVote: number; status: string };
  reviews: { userId: number; review: string }[];
  reputation: number;
  published: string;
}

export const AGENTS: AgentData[] = [
  {
    name: "CustomerCare Pro",
    id: "customer-care-pro",
    description: "Advanced customer service agent that handles inquiries, complaints, and support tickets with human-like empathy and efficiency. Perfect for businesses looking to provide 24/7 support.",
    longDescription: "CustomerCare Pro is designed for businesses that want to automate their customer support with a human touch. It can handle inquiries, complaints, and support tickets, and is trained on thousands of real-world interactions.",
    category: "Customer Service",
    rating: 4.9,
    downloads: "12.5K",
    verified: true,
    price: "$29/mo",
    image: "🎧",
    trustScore: 95,
    developer: "@customer_dev",
    stats: { successRate: 98.5, uptime: 99.9 },
    howItWorks: "Uses advanced NLP to understand customer inquiries and provide helpful, empathetic responses.",
    keyFeatures: ["Multi-language support", "Sentiment analysis", "Automated ticket routing", "Response templates"],
    audit: { daoVote: 423, status: "Passed" },
    reviews: [{ userId: 123, review: "Excellent customer service agent. Helped resolve my issue quickly!" }],
    reputation: 4.8,
    published: "2 months ago"
  },
  {
    name: "DataMiner AI",
    id: "dataminer-ai",
    description: "Powerful data analysis agent that extracts insights, generates reports, and identifies trends from your business data.",
    longDescription: "DataMiner AI transforms raw business data into actionable intelligence. It generates reports, identifies trends, and helps you make data-driven decisions.",
    category: "Analytics",
    rating: 4.8,
    downloads: "8.2K",
    verified: true,
    price: "$49/mo",
    image: "📊",
    trustScore: 92,
    developer: "@data_scientist",
    stats: { successRate: 97.2, uptime: 99.7 },
    howItWorks: "Connects to your data sources, analyzes data, and provides insights via dashboards and reports.",
    keyFeatures: ["Automated reporting", "Trend detection", "Data visualization", "Export to CSV"],
    audit: { daoVote: 388, status: "Passed" },
    reviews: [{ userId: 234, review: "Great for business analytics. Saved us hours every week!" }],
    reputation: 4.7,
    published: "1 month ago"
  },
  {
    name: "SocialGuru",
    id: "socialguru",
    description: "Social media management agent that creates content, schedules posts, and engages with your audience across platforms.",
    longDescription: "SocialGuru boosts your social media presence by automating content creation, scheduling, and engagement. Perfect for brands and influencers.",
    category: "Marketing",
    rating: 4.7,
    downloads: "15.1K",
    verified: true,
    price: "$19/mo",
    image: "📱",
    trustScore: 88,
    developer: "@ai_builder",
    stats: { successRate: 95.1, uptime: 99.5 },
    howItWorks: "Integrates with all major social platforms to automate posting and audience engagement.",
    keyFeatures: ["Content scheduling", "Audience analytics", "Auto-reply to comments", "Multi-platform support"],
    audit: { daoVote: 401, status: "Passed" },
    reviews: [{ userId: 345, review: "Helped us grow our followers by 30% in 2 months!" }],
    reputation: 4.6,
    published: "3 weeks ago"
  },
  {
    name: "CodeReview Bot",
    id: "codereview-bot",
    description: "Intelligent code review agent that analyzes pull requests, suggests improvements, and ensures code quality standards.",
    longDescription: "CodeReview Bot helps developers maintain high code quality by automatically reviewing pull requests, suggesting improvements, and enforcing best practices.",
    category: "Development",
    rating: 4.9,
    downloads: "6.8K",
    verified: true,
    price: "$39/mo",
    image: "💻",
    trustScore: 96,
    developer: "@dev_ops",
    stats: { successRate: 99.1, uptime: 99.8 },
    howItWorks: "Hooks into your repository to review code, check for bugs, and suggest improvements.",
    keyFeatures: ["Automated code review", "Style enforcement", "Security checks", "Pull request comments"],
    audit: { daoVote: 410, status: "Passed" },
    reviews: [{ userId: 456, review: "Caught several bugs before they hit production!" }],
    reputation: 4.9,
    published: "1 month ago"
  },
  {
    name: "InvoiceGenius",
    id: "invoicegenius",
    description: "Automated invoicing agent that generates, sends, and tracks invoices while managing payment reminders and reporting.",
    longDescription: "InvoiceGenius streamlines your billing process by automating invoice generation, delivery, and payment tracking.",
    category: "Finance",
    rating: 4.6,
    downloads: "9.3K",
    verified: true,
    price: "$25/mo",
    image: "💰",
    trustScore: 85,
    developer: "@fintech_pro",
    stats: { successRate: 96.3, uptime: 99.6 },
    howItWorks: "Connects to your accounting software to automate invoicing and payment reminders.",
    keyFeatures: ["Automated invoicing", "Payment reminders", "Reporting dashboard", "Multi-currency support"],
    audit: { daoVote: 415, status: "Passed" },
    reviews: [{ userId: 567, review: "No more late payments!" }],
    reputation: 4.5,
    published: "2 months ago"
  },
  {
    name: "ContentCraft AI",
    id: "contentcraft-ai",
    description: "Creative writing agent that produces blog posts, articles, and marketing copy tailored to your brand voice and style.",
    longDescription: "ContentCraft AI helps marketers and writers generate high-quality content quickly and efficiently.",
    category: "Content",
    rating: 4.8,
    downloads: "11.7K",
    verified: true,
    price: "$35/mo",
    image: "✍️",
    trustScore: 90,
    developer: "@content_guru",
    stats: { successRate: 97.8, uptime: 99.7 },
    howItWorks: "Uses AI to generate content based on your brand guidelines and target audience.",
    keyFeatures: ["Blog/article writing", "Brand voice adaptation", "SEO optimization", "Plagiarism check"],
    audit: { daoVote: 420, status: "Passed" },
    reviews: [{ userId: 678, review: "Content quality is top-notch!" }],
    reputation: 4.7,
    published: "1 month ago"
  },
  {
    name: "ShopAssistant",
    id: "shopassistant",
    description: "E-commerce assistant that helps customers find products, process orders, and provide shopping recommendations.",
    longDescription: "ShopAssistant improves your e-commerce experience by guiding customers, processing orders, and making personalized recommendations.",
    category: "E-commerce",
    rating: 4.5,
    downloads: "7.4K",
    verified: true,
    price: "$22/mo",
    image: "🛒",
    trustScore: 82,
    developer: "@ecom_expert",
    stats: { successRate: 94.2, uptime: 99.3 },
    howItWorks: "Integrates with your online store to assist customers and manage orders.",
    keyFeatures: ["Product recommendations", "Order processing", "Customer support", "Upsell/cross-sell"],
    audit: { daoVote: 425, status: "Passed" },
    reviews: [{ userId: 789, review: "Increased our sales by 15%!" }],
    reputation: 4.4,
    published: "3 weeks ago"
  },
  {
    name: "TechSupport Pro",
    id: "techsupport-pro",
    description: "Technical support agent that troubleshoots issues, provides solutions, and guides users through technical problems.",
    longDescription: "TechSupport Pro is your 24/7 tech support agent, ready to solve problems and guide users step-by-step.",
    category: "Support",
    rating: 4.7,
    downloads: "13.2K",
    verified: true,
    price: "$28/mo",
    image: "🔧",
    trustScore: 89,
    developer: "@support_guy",
    stats: { successRate: 97.5, uptime: 99.8 },
    howItWorks: "Uses a knowledge base and AI to troubleshoot and resolve technical issues.",
    keyFeatures: ["24/7 support", "Step-by-step guides", "Remote troubleshooting", "Ticket escalation"],
    audit: { daoVote: 430, status: "Passed" },
    reviews: [{ userId: 890, review: "Solved my issue in minutes!" }],
    reputation: 4.8,
    published: "2 weeks ago"
  },
  {
    name: "StudyBuddy AI",
    id: "studybuddy-ai",
    description: "Educational assistant that helps students with homework, explains concepts, and provides learning resources.",
    longDescription: "StudyBuddy AI is a virtual tutor for students, offering homework help, explanations, and study resources.",
    category: "Education",
    rating: 4.6,
    downloads: "10.8K",
    verified: true,
    price: "$15/mo",
    image: "📚",
    trustScore: 87,
    developer: "@edu_helper",
    stats: { successRate: 95.9, uptime: 99.4 },
    howItWorks: "Uses AI to answer questions, explain concepts, and recommend resources.",
    keyFeatures: ["Homework help", "Concept explanations", "Resource recommendations", "Progress tracking"],
    audit: { daoVote: 435, status: "Passed" },
    reviews: [{ userId: 901, review: "Helped me ace my exams!" }],
    reputation: 4.7,
    published: "1 week ago"
  },
  {
    name: "HealthAdvisor",
    id: "healthadvisor",
    description: "Healthcare assistant that provides health information, symptom checking, and wellness recommendations.",
    longDescription: "HealthAdvisor offers reliable health information, symptom checks, and wellness tips for users.",
    category: "Healthcare",
    rating: 4.4,
    downloads: "5.9K",
    verified: true,
    price: "$32/mo",
    image: "🏥",
    trustScore: 78,
    developer: "@health_guru",
    stats: { successRate: 93.7, uptime: 99.2 },
    howItWorks: "Uses medical databases and AI to provide health info and recommendations.",
    keyFeatures: ["Symptom checker", "Wellness tips", "Health info", "Appointment reminders"],
    audit: { daoVote: 440, status: "Passed" },
    reviews: [{ userId: 912, review: "Very helpful for quick health questions." }],
    reputation: 4.3,
    published: "2 weeks ago"
  },
  {
    name: "LegalEagle",
    id: "legaleagle",
    description: "Legal assistant that helps with document review, legal research, and basic legal guidance.",
    longDescription: "LegalEagle assists with legal document review, research, and provides basic legal guidance (not a substitute for a lawyer).",
    category: "Legal",
    rating: 4.3,
    downloads: "4.7K",
    verified: true,
    price: "$45/mo",
    image: "⚖️",
    trustScore: 75,
    developer: "@legal_bot",
    stats: { successRate: 91.2, uptime: 99.1 },
    howItWorks: "Uses legal databases and AI to review documents and answer legal questions.",
    keyFeatures: ["Document review", "Legal research", "Basic guidance", "Case tracking"],
    audit: { daoVote: 445, status: "Passed" },
    reviews: [{ userId: 923, review: "Quick and easy legal help!" }],
    reputation: 4.2,
    published: "1 week ago"
  },
  {
    name: "EmailOptimizer",
    id: "emailoptimizer",
    description: "Email marketing agent that optimizes campaigns, analyzes performance, and suggests improvements.",
    longDescription: "EmailOptimizer helps marketers improve their email campaigns with analytics, optimization tips, and performance tracking.",
    category: "Marketing",
    rating: 4.5,
    downloads: "8.9K",
    verified: true,
    price: "$18/mo",
    image: "📧",
    trustScore: 84,
    developer: "@email_marketer",
    stats: { successRate: 94.8, uptime: 99.3 },
    howItWorks: "Analyzes email campaigns and provides actionable suggestions for improvement.",
    keyFeatures: ["Campaign analytics", "A/B testing", "Performance tracking", "Optimization tips"],
    audit: { daoVote: 450, status: "Passed" },
    reviews: [{ userId: 934, review: "Open rates went up 10%!" }],
    reputation: 4.4,
    published: "5 days ago"
  },
  {
    name: "BudgetTracker",
    id: "budgettracker",
    description: "Personal finance agent that tracks expenses, creates budgets, and provides financial insights.",
    longDescription: "BudgetTracker helps individuals manage their finances by tracking expenses, creating budgets, and offering insights.",
    category: "Finance",
    rating: 4.6,
    downloads: "12.1K",
    verified: true,
    price: "$12/mo",
    image: "📈",
    trustScore: 86,
    developer: "@budget_guru",
    stats: { successRate: 95.5, uptime: 99.6 },
    howItWorks: "Connects to your bank accounts to track spending and help you stay on budget.",
    keyFeatures: ["Expense tracking", "Budget creation", "Spending insights", "Goal setting"],
    audit: { daoVote: 455, status: "Passed" },
    reviews: [{ userId: 945, review: "Finally got my spending under control!" }],
    reputation: 4.5,
    published: "3 days ago"
  },
  {
    name: "DevOps Helper",
    id: "devops-helper",
    description: "DevOps automation agent that manages deployments, monitors systems, and optimizes infrastructure.",
    longDescription: "DevOps Helper automates deployment, monitoring, and infrastructure optimization for engineering teams.",
    category: "Development",
    rating: 4.8,
    downloads: "5.3K",
    verified: true,
    price: "$55/mo",
    image: "🚀",
    trustScore: 93,
    developer: "@devops_pro",
    stats: { successRate: 98.2, uptime: 99.9 },
    howItWorks: "Integrates with your CI/CD pipeline to automate deployments and monitor systems.",
    keyFeatures: ["Automated deployments", "System monitoring", "Alerting", "Infrastructure optimization"],
    audit: { daoVote: 460, status: "Passed" },
    reviews: [{ userId: 956, review: "Deployment is now a breeze!" }],
    reputation: 4.8,
    published: "2 days ago"
  },
  {
    name: "SEO Master",
    id: "seo-master",
    description: "SEO optimization agent that analyzes websites, suggests improvements, and tracks search rankings.",
    longDescription: "SEO Master helps businesses improve their search engine rankings with actionable SEO insights and tracking.",
    category: "Marketing",
    rating: 4.7,
    downloads: "9.6K",
    verified: true,
    price: "$38/mo",
    image: "🔍",
    trustScore: 91,
    developer: "@seo_guru",
    stats: { successRate: 96.7, uptime: 99.7 },
    howItWorks: "Analyzes your website and provides SEO recommendations and ranking reports.",
    keyFeatures: ["Site audit", "Keyword tracking", "SEO suggestions", "Competitor analysis"],
    audit: { daoVote: 465, status: "Passed" },
    reviews: [{ userId: 967, review: "Our Google ranking improved in weeks!" }],
    reputation: 4.6,
    published: "1 day ago"
  }
];
